#!/usr/bin/env node
import { promises as fs } from "node:fs";
import path from "node:path";

interface Args {
  name: string;
  id: string; // stable manifest identity (slug)
  short: string;
  color: string; // background color of the icon + manifest background_color
  theme: string; // theme_color
  letter: string;
  fg: string;
  publicDir: string;
  html: string;
  logo?: string;
}

function parseArgs(argv: string[]): Args {
  const m = new Map<string, string>();
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith("--")) {
      const key = a.slice(2);
      const val = argv[i + 1] && !argv[i + 1].startsWith("--") ? argv[++i] : "true";
      m.set(key, val);
    }
  }
  const name = m.get("name") ?? "";
  if (!name) fail("--name is required, e.g. make-pwa init --name \"pi\" --color \"#0f1117\"");
  const color = m.get("color") ?? m.get("bg") ?? "#0f1117";
  return {
    name,
    id: m.get("id") ?? slug(name),
    short: m.get("short") ?? name,
    color,
    theme: m.get("theme") ?? color,
    letter: (m.get("letter") ?? [...name][0] ?? "?").toUpperCase(),
    fg: m.get("fg") ?? contrastColor(color),
    publicDir: m.get("public") ?? "public",
    html: m.get("html") ?? "index.html",
    logo: m.get("logo"),
  };
}

/** Lowercase URL-safe slug, used as the stable PWA manifest `id`. */
function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

function fail(msg: string): never {
  console.error(`make-pwa: ${msg}`);
  process.exit(1);
}

/** Pick black or white text for legibility on the given hex background. */
function contrastColor(hex: string): string {
  const h = hex.replace("#", "");
  const n =
    h.length === 3 ? h.split("").map((c) => c + c).join("") : h.padEnd(6, "0");
  const r = parseInt(n.slice(0, 2), 16);
  const g = parseInt(n.slice(2, 4), 16);
  const b = parseInt(n.slice(4, 6), 16);
  const lum = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  return lum > 0.6 ? "#0f1117" : "#ffffff";
}

/** A simple lettermark: solid square, big centered initial. */
function lettermarkSvg(a: Args, opts: { rounded: boolean }): string {
  const size = 512;
  const radius = opts.rounded ? 112 : 0;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
  <rect width="${size}" height="${size}" rx="${radius}" ry="${radius}" fill="${a.color}"/>
  <text x="50%" y="52%" dy=".35em" text-anchor="middle" font-family="Helvetica, Arial, sans-serif" font-size="300" font-weight="700" fill="${a.fg}">${escapeXml(a.letter)}</text>
</svg>
`;
}

function escapeXml(s: string): string {
  return s.replace(/[<>&'"]/g, (c) =>
    ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", "'": "&apos;", '"': "&quot;" })[c]!,
  );
}

async function svgToPng(svg: string, size: number): Promise<Buffer> {
  const { Resvg } = await import("@resvg/resvg-js");
  const r = new Resvg(svg, {
    fitTo: { mode: "width", value: size },
    font: { loadSystemFonts: true, defaultFontFamily: "Helvetica" },
  });
  return Buffer.from(r.render().asPng());
}

async function exists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

async function writeIfChanged(p: string, content: string | Buffer): Promise<void> {
  await fs.mkdir(path.dirname(p), { recursive: true });
  await fs.writeFile(p, content);
  console.log(`  wrote ${p}`);
}

const swTemplate = (name: string) => `// Service worker for ${name} (generated by make-pwa).
//
// Minimal by design: it exists so the app is installable and can receive web
// push. It deliberately does NOT cache assets — rely on HTTP caching for that.
// For real offline support, migrate to vite-plugin-pwa.

self.addEventListener("install", () => self.skipWaiting());

// A fetch handler is REQUIRED for Chrome's install criteria — without one,
// \`beforeinstallprompt\` never fires (no install banner on Android, no install
// icon on desktop Chrome). Network pass-through; no caching by design.
self.addEventListener("fetch", () => {});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("push", (event) => {
  const data = event.data ? event.data.json() : {};
  event.waitUntil(
    self.registration.showNotification(data.title || ${JSON.stringify(name)}, {
      body: data.body || "",
      icon: "/icon-192x192.png",
      badge: "/icon-192x192.png",
      tag: data.tag,
      data: { url: data.url || "/" },
    }),
  );
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const url = event.notification.data?.url || "/";
  event.waitUntil(
    self.clients.matchAll({ type: "window", includeUncontrolled: true }).then((clients) => {
      const existing = clients.find((c) => c.url.includes(url) && "focus" in c);
      if (existing) return existing.focus();
      return self.clients.openWindow(url);
    }),
  );
});
`;

function manifest(a: Args): string {
  return JSON.stringify(
    {
      id: a.id,
      name: a.name,
      short_name: a.short,
      start_url: "/",
      display: "standalone",
      background_color: a.color,
      theme_color: a.theme,
      icons: [
        { src: "/icon-192x192.png", sizes: "192x192", type: "image/png" },
        { src: "/icon-512x512.png", sizes: "512x512", type: "image/png" },
        {
          src: "/icon-maskable-512x512.png",
          sizes: "512x512",
          type: "image/png",
          purpose: "maskable",
        },
      ],
    },
    null,
    2,
  );
}

const HEAD_TAGS = (a: Args) => [
  '<link rel="icon" type="image/svg+xml" href="/favicon.svg" />',
  '<link rel="apple-touch-icon" href="/apple-touch-icon.png" />',
  '<link rel="manifest" href="/manifest.json" />',
  `<meta name="theme-color" content="${a.theme}" />`,
  '<meta name="mobile-web-app-capable" content="yes" />',
  '<meta name="apple-mobile-web-app-capable" content="yes" />',
  '<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />',
  `<meta name="apple-mobile-web-app-title" content="${a.short}" />`,
];

async function patchHtml(a: Args): Promise<void> {
  if (!(await exists(a.html))) {
    console.log(`  skipped ${a.html} (not found) — add these tags to your <head> manually:`);
    HEAD_TAGS(a).forEach((t) => console.log(`    ${t}`));
    return;
  }
  let html = await fs.readFile(a.html, "utf8");
  const missing = HEAD_TAGS(a).filter((tag) => {
    // crude idempotency: match on the rel/name marker so we don't double-insert
    const marker = tag.match(/(rel="[^"]+"|name="[^"]+")/)?.[0];
    return marker ? !html.includes(marker) : !html.includes(tag);
  });
  if (missing.length === 0) {
    console.log(`  ${a.html} already has PWA tags — no change`);
    return;
  }
  const block = "    " + missing.join("\n    ") + "\n  ";
  if (html.includes("</head>")) {
    html = html.replace("</head>", block + "</head>");
  } else {
    html = block + html;
  }
  await fs.writeFile(a.html, html);
  console.log(`  patched ${a.html} (+${missing.length} tags)`);
}

async function init(argv: string[]): Promise<void> {
  const a = parseArgs(argv);
  console.log(`make-pwa: scaffolding "${a.name}" into ${a.publicDir}/`);

  // favicon.svg — either the supplied logo or a generated lettermark.
  let faviconSvg: string;
  let pngSourceRounded: string;
  let pngSourceSquare: string;
  if (a.logo) {
    if (!a.logo.endsWith(".svg")) fail("--logo must be an .svg file");
    faviconSvg = await fs.readFile(a.logo, "utf8");
    pngSourceRounded = faviconSvg;
    pngSourceSquare = faviconSvg;
  } else {
    faviconSvg = lettermarkSvg(a, { rounded: true });
    pngSourceRounded = faviconSvg;
    pngSourceSquare = lettermarkSvg(a, { rounded: false });
  }

  await writeIfChanged(path.join(a.publicDir, "favicon.svg"), faviconSvg);
  await writeIfChanged(path.join(a.publicDir, "icon-192x192.png"), await svgToPng(pngSourceRounded, 192));
  await writeIfChanged(path.join(a.publicDir, "icon-512x512.png"), await svgToPng(pngSourceRounded, 512));
  await writeIfChanged(path.join(a.publicDir, "icon-maskable-512x512.png"), await svgToPng(pngSourceSquare, 512));
  await writeIfChanged(path.join(a.publicDir, "apple-touch-icon.png"), await svgToPng(pngSourceSquare, 180));
  await writeIfChanged(path.join(a.publicDir, "manifest.json"), manifest(a));
  await writeIfChanged(path.join(a.publicDir, "sw.js"), swTemplate(a.name));
  await patchHtml(a);

  console.log("\nmake-pwa: done. Final step — mount the banner in your app root:\n");
  console.log(`  import { PwaInstall } from "make-pwa";`);
  console.log(`  // ...render near the top of your app tree:`);
  console.log(`  <PwaInstall appName="${a.name}" />\n`);
}

const [cmd, ...rest] = process.argv.slice(2);
switch (cmd) {
  case "init":
    init(rest).catch((e) => fail(e?.message ?? String(e)));
    break;
  default:
    console.log(`make-pwa — turn a React/Vite app into an installable PWA.

Usage:
  make-pwa init --name "<App>" [options]

Options:
  --name <str>      App name (required)
  --short <str>     Short name for the home screen (default: name)
  --color <hex>     Icon background + manifest background_color (default: #0f1117)
  --theme <hex>     theme_color / status bar color (default: --color)
  --letter <char>   Icon letter (default: first letter of name)
  --fg <hex>        Icon letter color (default: auto-contrast)
  --logo <file.svg> Use this SVG instead of a generated lettermark
  --public <dir>    Public/static dir (default: public)
  --html <file>     index.html to patch (default: index.html)

Writes manifest.json, sw.js and icons into the public dir, patches index.html,
then prints the one component to add.`);
    if (cmd && cmd !== "help") process.exit(1);
}
